
#pragma once

#include "OSThread.h"
#include "json.h"

class CWebThread : public OSThread
{
public:
	CWebThread();
	~CWebThread();
public:
	GM_Error	InitThread();							// 初始化线程...
	void		doPostCurl(char *pData, size_t nSize);	// 处理汇报反馈...
private:
	virtual void	Entry();				// 线程函数...
	bool			LogoutHaoYi();			// 采集端从中心退出...
	bool			LogoutGather();			// 采集端从节点退出...
	bool			RegisterHaoYi();		// 验证许可证...
	bool			RegisterGather();		// 注册采集端...
	bool			GetAllCameraData();		// 获取通道配置...
	bool			parseJson(Json::Value & outValue);
private:
	enum {
		kRegGather = 0,					// 正在注册采集端...
		kRegHaoYi = 1,					// 正在验证许可证...
		kGetCamera = 2,					// 正在获取通道...
		kRegCamera = 3,					// 正在注册通道(添加或修改)...
		kDelCamera = 4,					// 正在删除摄像头...
		kStatCamera = 5,				// 正在汇报通道状态...
		kGatherLogout = 6,				// 采集端退出汇报...
	}m_eRegState;
private:
	string			m_strUTF8Data;		// 统一的反馈数据...
};